# Generated by Django 3.0.2 on 2020-01-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre y Apellidos')),
                ('intolerancia', models.CharField(choices=[(' ', ' '), ('Diabético', 'Diabético'), ('Celiaco', 'Celiaco'), ('Intolerante a la lactosa', 'Intolerante a la lactosa'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano')], default=' ', max_length=24, verbose_name='Intolerancia')),
                ('transporte', models.BooleanField(verbose_name='Transporte')),
            ],
        ),
    ]
