# Generated by Django 3.0.2 on 2020-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='intolerancia',
            field=models.CharField(choices=[(' ', ' '), ('Diabético', 'Diabético'), ('Celiaco', 'Celiaco'), ('Intolerante a la lactosa', 'Intolerante a la lactosa'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano'), ('Otros', 'Otros')], default=' ', max_length=24, verbose_name='Intolerancia'),
        ),
    ]
